spring:
  application:
    name: control-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/baro_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

mqtt:
  mode: ${MQTT_MODE:local}
  client-id: control-service
  local:
    host: ${LOCAL_MQTT_HOST:localhost}
    port: ${LOCAL_MQTT_PORT:1883}
  aws:
    endpoint: ${IOT_ENDPOINT:}
    cert-path: ${IOT_CERT_PATH:}
    key-path: ${IOT_KEY_PATH:}
    ca-path: ${IOT_CA_PATH:}
    port: ${IOT_PORT:8883}

kafka:
  topic:
    vehicle-data: ${KAFKA_TOPIC:vehicle-data-topic}

dispatch:
  service:
    url: ${DISPATCH_SERVICE_URL:http://localhost:8082}
